fail_fast: true
repos:
  - repo: builtin
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: \.md$
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.9
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]

  - repo: local
    hooks:
      - id: rumdl
        name: rumdl fmt & check
        language: system
        entry: rumdl fmt && rumdl check
        files: \.md$
        pass_filenames: true
        require_serial: true

